/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'displayName' : IDL.Text,
  'displayEmoji' : IDL.Text,
});
export const RestaurantInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Review = IDL.Record({
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'displayName' : IDL.Text,
    'displayEmoji' : IDL.Text,
  });
  const RestaurantInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const Review = IDL.Record({
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
  });
  
  return IDL.Service({
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };